### ISSUE TITLE
Releasing the data on other platforms

### ISSUE THREAD

**Issue by xhluca** [McGill-NLP/bias-bench#1]
It seems the WIki-2.5 data is currently only accessible through Google Drive. I believe GDrive has download limit and it's difficult to programmatically download it. I suggest releasing on the following platforms:

* GitHub releases (you can make a special release with a tag like `data-v1`
* Huggingface Datasets

The latter has a library to facilitate download. As for the former, I believe it would be nice to bundle it inside the `bias-bench` library, so you can do:

```python
import bias_bench

wiki_data = bias_bench.util.download_data(version="data-v1")
```

**Comment by ncmeade** [comment]
Closing this for now, I will revisit this when refactoring the repository in the future.
