### ISSUE TITLE
Cannot reproduce the same gender SEAT score for original GPT2

### ISSUE THREAD

**Issue by realliyifei** [McGill-NLP/bias-bench#12]
I cannot reproduce the same gender SEAT score for GPT2 (gpt2). Following your source code in `seat.sh` and `seat.py`, I use 

```
model = transformers.GPT2Model.from_pretrained('gpt2', output_hidden_states=True)
tokenizer = AutoTokenizer.from_pretrained('gpt2')
```

The SEAT average absolute score of the original GPT2 from my side is different than your Table 10.

Note that I am kinda sure my other code is correct since I can reproduce BERT's SEAT (bert-base-uncased) by the code

```
model = transformers.BertModel.from_pretrained('bert-base-uncased', output_hidden_states=True)
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
```

Did I misunderstand the GPT2 model that you used? Or is there any other idea you have about why the SEAT is inconsistent here? Thanks!

**Comment by ncmeade** [comment]
Hi @realliyifei,

Thank you for raising the issue! 

Before I dig in more, I just wanted to confirm you are computing the average absolute effect size and not the average effect size?

**Comment by realliyifei** [comment]
thanks; yes it is average absolute SEAT

**Comment by ncmeade** [comment]
Interesting. I just re-ran the code and I'm able to reproduce the results. Have you customized the code? Also, just to confirm, you are running SEAT-6, SEAT-6b, SEAT-7, SEAT-7b, SEAT-8, and SEAT-8b?

**Comment by realliyifei** [comment]
Thanks for your help! I didn't change the SEAT code nor the SEAT list, otherwise, I won't be able to reproduce the SEAT score successfully on BERT ('bert-base-uncased'). I think BERT and GPT2 share the exactly same SEAT pipeline. 

I will re-run your source code later, but could you confirm first that for GPT2, the `model` is 'GPT2Model', `model_name_or_path` is 'gpt2', and the `tokenizer` is 'AutoTokenizer'? That is:

```
model = transformers.GPT2Model.from_pretrained('gpt2', output_hidden_states=True)
tokenizer = AutoTokenizer.from_pretrained('gpt2')
```

**Comment by ncmeade** [comment]
Yes, the `model` is `GPT2Model` and the `model_name_or_path` is `gpt2`.

One possibility is that you are computing the average over the wrong SEAT tests. Table 10 contains the gender scores only, so if you average across all of the SEAT tests (`seat.sh` will compute all the tests), you'll get incorrect results. I'd suggest double-checking that you are averaging only across SEAT-6, SEAT-6b, SEAT-7, SEAT-7b, SEAT-8, and SEAT-8b. 

Let me know if this works.

**Comment by realliyifei** [comment]
The SEAT is the same but the score is still different. Perhaps it is due to the environment or package version. I just close it now. Thanks for helping!

**Comment by ncmeade** [comment]
Great. Feel free to re-open this if you'd like to dig in further.
