### ISSUE TITLE
Question regarding SEAT implementation

### ISSUE THREAD

**Issue by Ewanwong** [McGill-NLP/bias-bench#13]
Hello,  first of all thank you for your fantastic work! I have a question regarding how you extract sentence encoding in SEAT experiments. It seems like you average over all token's last layer representation as sentence embedding, which is different from the original SEAT work. Did I understand it correctly? I'm just curious how you run SEAT test with generative models like gpt-2.

**Comment by ncmeade** [comment]
Hi @Ewanwong,

Sorry for the delayed response---glad you find the code useful!

Yes, exactly. We average over the final layer of token representations for all the models we evaluate.

Let me know if this makes sense. Happy to answer any other questions as well.

**Comment by Ewanwong** [comment]
That makes sense. Thank you for your explanation!
