### ISSUE TITLE
Testing BLOOM

### ISSUE THREAD

**Issue by MartaMarchiori** [McGill-NLP/bias-bench#17]
Thanks for your amazing work :) 

Using the transformer version indicated in the requirements (transformers==4.16.2), I cannot access BLOOM. 

If I use the last transformer version, I get a bunch of errors w.r.t. generation.py file in the self_debias folder, e.g. about the SampleOutput that cannot be imported/is not defined. 

Could you help me? :)

**Comment by ncmeade** [comment]
Hi @MartaMarchiori,

Thanks for your interest in our work and I'm sorry for the very late response!

W.r.t getting Self-Debias working for BLOOM, perhaps removing the `SampleOutput` import may fix the compatibility issues? I see that `SampleOutput` is just used as a type annotation so it shouldn't impact the code, generally.

**Comment by ncmeade** [comment]
Closing this now. Feel free to reopen for further discussion!
