### ISSUE TITLE
Consider adjustments to support local model paths.

### ISSUE THREAD

**Issue by ecrows** [McGill-NLP/bias-bench#20]
Currently the experiments code uses the "model_name_or_path" argument, but forces a number of predefined Huggingface model names.  I took a brief look at `crows.py` and with some minor modifications (namely an adjustment to `generate_experiment_id` to accommodate paths) and relaxing the parameter requirement, the benchmark can be run on local models.

I may be able to send a PR if that would be helpful!

**Comment by ncmeade** [comment]
Hi @ecrows,

Sorry for the delayed response---yes, if you'd like to add this functionality feel free to send a PR! The current experiment ID creation is quite brittle.
