### ISSUE TITLE
Special BLANK positions.

### ISSUE THREAD

**Issue by xxupiano** [McGill-NLP/bias-bench#21]
1. The context starts with BLANK. In this situation, a blank space is unnecessary before template_word with RoBERTa.
2. Here is a case in the intrasentence set of StereoSet 'WitchDoctors and priests are different things. Brahmin are seen as both sometimes.BLANK', which needs to be handled specially or discarded directly. Actually, StereoSet is not clean. Some letters in the 'context' or 'target' are capitalized differently from those in the corresponding sentences.

**Comment by xxupiano** [comment]
Also, there may be more than one BLANK, such as 'brahmin is very BLANK and is strict about BLANK'.

**Comment by xxupiano** [comment]
Also, there may be more than one 'BLANK' in a context, such as 
'brahmin is very BLANK and is strict about BLANK'.

**Comment by ncmeade** [comment]
Hi @xxupiano, thank you for flagging this issue!

We're aware of some of the data quality issues with StereoSet and may revisit it in the future.

For now, we will not modify the code/dataset as we wish for this repository to serve as an artifact for reproducing the results from our paper.
