### ISSUE TITLE
There's no intersentence in the stereoset of bias bench

### ISSUE THREAD

**Issue by VelikayaScarlet** [McGill-NLP/bias-bench#22]
Evaluating predictions/stereoset_m-BertForMaskedLM_c-bert-base-uncased_s-42.json... # it's my custom model generated in bias bench
Traceback (most recent call last):
  File "/content/StereoSet/code/evaluation.py", line 193, in <module>
    parse_file(args.gold_file, prediction_file) 
  File "/content/StereoSet/code/evaluation.py", line 151, in parse_file
    score_evaluator = ScoreEvaluator(
  File "/content/StereoSet/code/evaluation.py", line 65, in __init__
    results[split][domain] = self.evaluate(self.domain2example[split][domain])
  File "/content/StereoSet/code/evaluation.py", line 76, in evaluate
    counts = self.count(examples)
  File "/content/StereoSet/code/evaluation.py", line 90, in count
    if (self.id2score[pro_id] > self.id2score[anti_id]):
KeyError: '6b56153532fa360d37c25e918546f571'
Perhaps the key value pairs in the bias bench may not match well with the stereoset，what should i do? I just want to evaluate my model with stereoset.

**Comment by ncmeade** [comment]
Hi @VelikayaScarlet,

Sorry for the late reply. We currently don't support the intersentence evaluation in this repository. The code from the original [StereoSet](https://github.com/moinnadeem/StereoSet) repository may be of use to you.

Hope this helps.

**Comment by ncmeade** [comment]
Closing this for now. Feel free to reopen if you have additional questions.
