### ISSUE TITLE
missing 1 required positional argument: 'trg_len'

### ISSUE THREAD

**Issue by yqw0710** [McGill-NLP/bias-bench#7]
hi,when i run experiments/stereoset_debias.py and select SelfDebiasGPT2LMHeadModel as model,I encountered a problem: A parameter value("trg_len") is missing when calling function "compute_loss_self_debiasing".I don't know how to solve this.
![image](https://user-images.githubusercontent.com/61569034/190144036-3a2b6caa-ab41-4de1-88da-d9e190c21e1e.png)
![image](https://user-images.githubusercontent.com/61569034/190144144-de7c5f1b-9ef0-4ef4-aabd-89100e5dd2c5.png)

**Comment by mourga** [comment]
Got the same error when running `crows_debias.py` for `GPT-2`. In `crows.py` line [308](https://github.com/McGill-NLP/bias-bench/blob/a62b313affd60a01d3bbb9b16ec801dd34b5bee6/bias_bench/benchmark/crows/crows.py#L308) the call for `self._model.compute_loss_self_debiasing(...)` does not pass any argument for `trg_len` (see [here](https://github.com/McGill-NLP/bias-bench/blob/a62b313affd60a01d3bbb9b16ec801dd34b5bee6/bias_bench/debias/self_debias/modeling.py#L254)).

**Comment by ncmeade** [comment]
Hi both, thank you for flagging this issue! I thought I had corrected this while cleaning up the code. I'll commit a fix in the next 1-2 days.

**Comment by yqw0710** [comment]
> Hi both, thank you for flagging this issue! I thought I had corrected this while cleaning up the code. I'll commit a fix in the next 1-2 days.

Thanks!

**Comment by yqw0710** [comment]
> 

Hello, sorry to bother you, can you update the code if you fix the problem?

**Comment by ncmeade** [comment]
Hi both, sorry for the delay. I've pushed a fix (0a5365e0279e52449f1d135ba2c222ec2c89b192) for this issue. Let me know if you're still having any problems. I plan to refactor much of this code in the near future.

**Comment by yqw0710** [comment]
Thank you for solving this problem! You plan to refactor this code is you have a new research progress?

**Comment by ncmeade** [comment]
No, just updating the current code in this repository.

I'll close this issue shortly. Feel free to re-open if there are other problems!

**Comment by yqw0710** [comment]
ok, thank you very much.
