### ISSUE TITLE
consult

### ISSUE THREAD

**Issue by struggle12** [McGill-NLP/bias-bench#9]
I have read this paper of yours -- An Empirical Survey of the Effectiveness of Debiasing Techniques for Pre-trained Language Models, and I have a question:  INLP and Sentence Debias are embedding debias methods.  StereoSet and CrowS-Pairs are measures of bias in mlm.  Why can these two measures be used to measure INLP and Sentence debias?

**Comment by ncmeade** [comment]
Hi @struggle12,

Indeed, INLP and SentenceDebias were originally proposed for debiasing representations (e.g., debiasing sentence representations in the case of SentenceDebias). We use INLP and SentenceDebias to debias a model's internal representations (e.g., the contextualized representations for MLMs). Following this, the debiased representations are fed into the model's language modeling head for prediction.

Hope this helps clear things up. Happy to answer any more questions!

**Comment by ncmeade** [comment]
Closing this now. Feel free to re-open if you have additional questions.
